/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardTokenRouteImport } from './routes/onboard.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedSalaryStructuresRouteImport } from './routes/_authenticated/salary/structures'
import { Route as AuthenticatedSalaryComponentsRouteImport } from './routes/_authenticated/salary/components'
import { Route as AuthenticatedPayrollRunRouteImport } from './routes/_authenticated/payroll/run'
import { Route as AuthenticatedPayrollHistoryRouteImport } from './routes/_authenticated/payroll/history'
import { Route as AuthenticatedPayrollIdRouteImport } from './routes/_authenticated/payroll/$id'
import { Route as AuthenticatedLeaveTypesRouteImport } from './routes/_authenticated/leave/types'
import { Route as AuthenticatedLeaveRequestsRouteImport } from './routes/_authenticated/leave/requests'
import { Route as AuthenticatedLeaveBalancesRouteImport } from './routes/_authenticated/leave/balances'
import { Route as AuthenticatedLeaveAttendanceRouteImport } from './routes/_authenticated/leave/attendance'
import { Route as AuthenticatedEmployeesNewRouteImport } from './routes/_authenticated/employees/new'
import { Route as AuthenticatedEmployeesIdRouteImport } from './routes/_authenticated/employees/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardTokenRoute = OnboardTokenRouteImport.update({
  id: '/onboard/$token',
  path: '/onboard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalaryStructuresRoute =
  AuthenticatedSalaryStructuresRouteImport.update({
    id: '/salary/structures',
    path: '/salary/structures',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalaryComponentsRoute =
  AuthenticatedSalaryComponentsRouteImport.update({
    id: '/salary/components',
    path: '/salary/components',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollRunRoute = AuthenticatedPayrollRunRouteImport.update({
  id: '/payroll/run',
  path: '/payroll/run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollHistoryRoute =
  AuthenticatedPayrollHistoryRouteImport.update({
    id: '/payroll/history',
    path: '/payroll/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollIdRoute = AuthenticatedPayrollIdRouteImport.update({
  id: '/payroll/$id',
  path: '/payroll/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveTypesRoute = AuthenticatedLeaveTypesRouteImport.update({
  id: '/leave/types',
  path: '/leave/types',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRequestsRoute =
  AuthenticatedLeaveRequestsRouteImport.update({
    id: '/leave/requests',
    path: '/leave/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaveBalancesRoute =
  AuthenticatedLeaveBalancesRouteImport.update({
    id: '/leave/balances',
    path: '/leave/balances',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaveAttendanceRoute =
  AuthenticatedLeaveAttendanceRouteImport.update({
    id: '/leave/attendance',
    path: '/leave/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesNewRoute =
  AuthenticatedEmployeesNewRouteImport.update({
    id: '/employees/new',
    path: '/employees/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesIdRoute =
  AuthenticatedEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/leave/attendance': typeof AuthenticatedLeaveAttendanceRoute
  '/leave/balances': typeof AuthenticatedLeaveBalancesRoute
  '/leave/requests': typeof AuthenticatedLeaveRequestsRoute
  '/leave/types': typeof AuthenticatedLeaveTypesRoute
  '/payroll/$id': typeof AuthenticatedPayrollIdRoute
  '/payroll/history': typeof AuthenticatedPayrollHistoryRoute
  '/payroll/run': typeof AuthenticatedPayrollRunRoute
  '/salary/components': typeof AuthenticatedSalaryComponentsRoute
  '/salary/structures': typeof AuthenticatedSalaryStructuresRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/leave/attendance': typeof AuthenticatedLeaveAttendanceRoute
  '/leave/balances': typeof AuthenticatedLeaveBalancesRoute
  '/leave/requests': typeof AuthenticatedLeaveRequestsRoute
  '/leave/types': typeof AuthenticatedLeaveTypesRoute
  '/payroll/$id': typeof AuthenticatedPayrollIdRoute
  '/payroll/history': typeof AuthenticatedPayrollHistoryRoute
  '/payroll/run': typeof AuthenticatedPayrollRunRoute
  '/salary/components': typeof AuthenticatedSalaryComponentsRoute
  '/salary/structures': typeof AuthenticatedSalaryStructuresRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/_authenticated/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/_authenticated/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/_authenticated/leave/attendance': typeof AuthenticatedLeaveAttendanceRoute
  '/_authenticated/leave/balances': typeof AuthenticatedLeaveBalancesRoute
  '/_authenticated/leave/requests': typeof AuthenticatedLeaveRequestsRoute
  '/_authenticated/leave/types': typeof AuthenticatedLeaveTypesRoute
  '/_authenticated/payroll/$id': typeof AuthenticatedPayrollIdRoute
  '/_authenticated/payroll/history': typeof AuthenticatedPayrollHistoryRoute
  '/_authenticated/payroll/run': typeof AuthenticatedPayrollRunRoute
  '/_authenticated/salary/components': typeof AuthenticatedSalaryComponentsRoute
  '/_authenticated/salary/structures': typeof AuthenticatedSalaryStructuresRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/onboard/$token'
    | '/employees/$id'
    | '/employees/new'
    | '/leave/attendance'
    | '/leave/balances'
    | '/leave/requests'
    | '/leave/types'
    | '/payroll/$id'
    | '/payroll/history'
    | '/payroll/run'
    | '/salary/components'
    | '/salary/structures'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/onboard/$token'
    | '/employees/$id'
    | '/employees/new'
    | '/leave/attendance'
    | '/leave/balances'
    | '/leave/requests'
    | '/leave/types'
    | '/payroll/$id'
    | '/payroll/history'
    | '/payroll/run'
    | '/salary/components'
    | '/salary/structures'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/onboard/$token'
    | '/_authenticated/employees/$id'
    | '/_authenticated/employees/new'
    | '/_authenticated/leave/attendance'
    | '/_authenticated/leave/balances'
    | '/_authenticated/leave/requests'
    | '/_authenticated/leave/types'
    | '/_authenticated/payroll/$id'
    | '/_authenticated/payroll/history'
    | '/_authenticated/payroll/run'
    | '/_authenticated/salary/components'
    | '/_authenticated/salary/structures'
    | '/_authenticated/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardTokenRoute: typeof OnboardTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/$token': {
      id: '/onboard/$token'
      path: '/onboard/$token'
      fullPath: '/onboard/$token'
      preLoaderRoute: typeof OnboardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salary/structures': {
      id: '/_authenticated/salary/structures'
      path: '/salary/structures'
      fullPath: '/salary/structures'
      preLoaderRoute: typeof AuthenticatedSalaryStructuresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salary/components': {
      id: '/_authenticated/salary/components'
      path: '/salary/components'
      fullPath: '/salary/components'
      preLoaderRoute: typeof AuthenticatedSalaryComponentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/run': {
      id: '/_authenticated/payroll/run'
      path: '/payroll/run'
      fullPath: '/payroll/run'
      preLoaderRoute: typeof AuthenticatedPayrollRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/history': {
      id: '/_authenticated/payroll/history'
      path: '/payroll/history'
      fullPath: '/payroll/history'
      preLoaderRoute: typeof AuthenticatedPayrollHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/$id': {
      id: '/_authenticated/payroll/$id'
      path: '/payroll/$id'
      fullPath: '/payroll/$id'
      preLoaderRoute: typeof AuthenticatedPayrollIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave/types': {
      id: '/_authenticated/leave/types'
      path: '/leave/types'
      fullPath: '/leave/types'
      preLoaderRoute: typeof AuthenticatedLeaveTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave/requests': {
      id: '/_authenticated/leave/requests'
      path: '/leave/requests'
      fullPath: '/leave/requests'
      preLoaderRoute: typeof AuthenticatedLeaveRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave/balances': {
      id: '/_authenticated/leave/balances'
      path: '/leave/balances'
      fullPath: '/leave/balances'
      preLoaderRoute: typeof AuthenticatedLeaveBalancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave/attendance': {
      id: '/_authenticated/leave/attendance'
      path: '/leave/attendance'
      fullPath: '/leave/attendance'
      preLoaderRoute: typeof AuthenticatedLeaveAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/new': {
      id: '/_authenticated/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthenticatedEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/$id': {
      id: '/_authenticated/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AuthenticatedEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesIdRoute: typeof AuthenticatedEmployeesIdRoute
  AuthenticatedEmployeesNewRoute: typeof AuthenticatedEmployeesNewRoute
  AuthenticatedLeaveAttendanceRoute: typeof AuthenticatedLeaveAttendanceRoute
  AuthenticatedLeaveBalancesRoute: typeof AuthenticatedLeaveBalancesRoute
  AuthenticatedLeaveRequestsRoute: typeof AuthenticatedLeaveRequestsRoute
  AuthenticatedLeaveTypesRoute: typeof AuthenticatedLeaveTypesRoute
  AuthenticatedPayrollIdRoute: typeof AuthenticatedPayrollIdRoute
  AuthenticatedPayrollHistoryRoute: typeof AuthenticatedPayrollHistoryRoute
  AuthenticatedPayrollRunRoute: typeof AuthenticatedPayrollRunRoute
  AuthenticatedSalaryComponentsRoute: typeof AuthenticatedSalaryComponentsRoute
  AuthenticatedSalaryStructuresRoute: typeof AuthenticatedSalaryStructuresRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesIdRoute: AuthenticatedEmployeesIdRoute,
  AuthenticatedEmployeesNewRoute: AuthenticatedEmployeesNewRoute,
  AuthenticatedLeaveAttendanceRoute: AuthenticatedLeaveAttendanceRoute,
  AuthenticatedLeaveBalancesRoute: AuthenticatedLeaveBalancesRoute,
  AuthenticatedLeaveRequestsRoute: AuthenticatedLeaveRequestsRoute,
  AuthenticatedLeaveTypesRoute: AuthenticatedLeaveTypesRoute,
  AuthenticatedPayrollIdRoute: AuthenticatedPayrollIdRoute,
  AuthenticatedPayrollHistoryRoute: AuthenticatedPayrollHistoryRoute,
  AuthenticatedPayrollRunRoute: AuthenticatedPayrollRunRoute,
  AuthenticatedSalaryComponentsRoute: AuthenticatedSalaryComponentsRoute,
  AuthenticatedSalaryStructuresRoute: AuthenticatedSalaryStructuresRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardTokenRoute: OnboardTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
